apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - issuer.yaml
  - service-account.yaml
labels:
  - includeSelectors: true
    pairs:
      app: etcd-operator
