apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-operator-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd-operator-leader-election
subjects:
  - kind: ServiceAccount
    name: etcd-operator