apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-operator
spec:
  template:
    spec:
      containers:
        - name: operator
          args:
            - "--watch-namespaces=$(POD_NAMESPACE)"
          env:
            - name: GOCOVERDIR
              value: /var/coverage
          volumeMounts:
            - name: coverage
              mountPath: /var/coverage
          resources:
            limits:
              cpu: 125m
              memory: 128M
            requests:
              cpu: 125m
              memory: 128M
      volumes:
        - name: coverage
          emptyDir: {}
