apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sandbox
resources:
  - ../base
  - role.yaml
  - service-account.yaml
  - test-role.yaml
  - test-service-account.yaml
patches:
  - path: deployment.yaml
