apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd-test
subjects:
  - kind: ServiceAccount
    name: etcd-test