apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fleet
resources:
  - role.yaml
  - leader-election-role.yaml
  - sidecar-role.yaml
  - role-binding.yaml
labels:
  - includeSelectors: true
    pairs:
      app: etcd-operator
