name: ci

on:
  push:

jobs:
  image-build:
    name: Image Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build images
        uses: hiberbee/github-action-skaffold@1.19.0
        with:
          skaffold-version: 2.14.1
          command: build
          file-output: build/images.json
      - name: Archive image tags
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: build/images.json